[tool]
[tool.poetry]
name = "cast_control"
version = "0.9.3"
description = "📺 Control Chromecasts from Linux and D-Bus"
license = "AGPL-3.0"
homepage = "https://github.com/alexdelorenzo/cast_control"
authors = ["Alex DeLorenzo"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.7"
appdirs = "==1.4.4"
click = "==8.0.1"
daemons = "==1.3.1"
mpris-server = "==0.2.18"
pychromecast = "==9.1.2"
pydbus = ">=0.6.0"
pygobject = ">=3.34.0"
cast_control = ">=0.9.1"
