#[build-system]
#requires = ["setuptools", "wheel", "setuptools-rust"]
#build-backend = "maturin"


[build-system]
requires = ["maturin>=0.10,<0.11"]
build-backend = "maturin"


[tool.maturin]
bindings = "cffi"
manylinux = "off"
#description="asdasdasdasd"
#sdist-include = ["dist/*"]