[tool.poetry]
name = "fastapi-opa"
version = "1.2.1"
description = "Fastapi OPA middleware incl. auth flow."
authors = ["Matthias Osswald <m@osswald.li>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/busykoala/fastapi-opa"
keywords = ["fastapi", "oidc", "authentication", "authorization", "saml"]

[tool.poetry.dependencies]
python = "^3.6"
fastapi = "^0.63.0"
requests = "^2.25.1"
PyJWT = {extras = ["crypto"], version = "^2.0.1"}
graphene = {version = "^2.1.8", optional = true}
python3-saml = {version = "^1.10.1", optional = true}
python-multipart = {version = "^0.0.5", optional = true}


[tool.poetry.dev-dependencies]
flake9 = "^3.8.3"
black = "^20.8b1"
isort = "^5.8.0"
bandit = "^1.7.0"
pytest = "^6.2.2"
pytest-mock = "^3.5.1"
mock = "^4.0.3"
freezegun = "^1.1.0"
Authlib = "^0.15.3"
pytest-asyncio = "^0.15.1"
nest-asyncio = "^1.5.1"

[tool.poetry.extras]
graphql = ["graphene"]
saml = ["python3-saml", "python-multipart"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 79

[tool.flake8]
max-complexity = 15
max-line-length = 79
extend-ignore = "E203"

[tool.isort]
line_length = 79
include_trailing_comma = true
force_single_line = true
