# Generated by Django 3.0.5 on 2021-05-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('expires_on', models.DateTimeField()),
                ('remaining_attempts', models.IntegerField(default=5)),
                ('can_send_otp_after', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
