"""
    Portal OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.telemetry_value import TelemetryValue


class TestTelemetryValue(unittest.TestCase):
    """TelemetryValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTelemetryValue(self):
        """Test TelemetryValue"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TelemetryValue()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
