"""
    Portal OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.machines_api import MachinesApi  # noqa: E501


class TestMachinesApi(unittest.TestCase):
    """MachinesApi unit test stubs"""

    def setUp(self):
        self.api = MachinesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_machines_list(self):
        """Test case for machines_list"""
        pass

    def test_machines_retrieve(self):
        """Test case for machines_retrieve"""
        pass


if __name__ == "__main__":
    unittest.main()
