[tool.poetry]
name = "fastql-packages"
version = "0.1.7"
description = ""
authors = ["Muhammad Abdurrahman <rachman.sd@gmail.com>"]
readme = 'readme.md'

[tool.poetry.dependencies]
python = ">=3.6,<4/0"
click = "^7.1.2"
requests = "^2.25.1"
colorama = "^0.4.4"
Jinja2 = "^3.0.0"
orator = "^0.9.9"
inflect = "^5.3.0"
passlib = "^1.7.4"
fastapi = "^0.65.1"
graphene = ">=3.0b5"
graphene-pydantic = "^0.2.0"
uvicorn = "^0.13.4"
python-dotenv = "^0.17.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
fastql = "fastql_packages.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
