[tool.poetry]
name = "pycorpus"
version = "2.3"
description = "Easy concurrent launch of series of file based experiments."
authors = ["Josu Bermudez <josubg@gmail.com>"]
license = "MIT"
classifiers=[
        'Development Status :: 4 - Beta',
        'Intended Audience :: Developers',
        'Intended Audience :: Science/Research',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'License :: OSI Approved :: Apache Software License',
        'Programming Language :: Python :: 3',
    ]
repository='https://github.com/josubg/pycorpus/'
keywords=['corpus']
readme='README.md'
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
lxml = "^4.6.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
