
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-29T15:51:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "32b3565a365a6c8d8abea1b1de5aed3e9496e15a",
 "version": "0.6.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
