[tool.poetry]
name = "chamyleon"
version = "0.1.0a1"
description = ""
authors = ["William C. Canin <william.costa.canin@gmail.com>"]
readme = "README.rst"

packages = [
    { include = "snakypy" }
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
