
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-27T22:58:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1ea27be17cb8c16be5273ccb053249e0ae0732a",
 "version": "1.0.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
