[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py36", "py37", "py38"]
include = "\\.pyi?$"

[tool.isort]
profile = "black"
line_length = 100

[tool.poetry]
name = "spiel"
version = "0.2.1"
description = "A framework for building and presenting richly-styled presentations in your terminal using Python."
readme="README.md"
homepage="https://github.com/JoshKarpel/spiel"
documentation="https://spiel.readthedocs.io/en/latest/"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: Console",
    "License :: OSI Approved :: MIT License",
    "Operating System :: MacOS",
    "Operating System :: Unix",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Multimedia :: Graphics :: Presentation",
    "Typing :: Typed"]
authors = ["JoshKarpel <josh.karpel@gmail.com>"]
license = "MIT"
include = ["py.typed", "demo/*"]

[tool.poetry.dependencies]
python = "^3.9"
rich = "^10.2.2"
typer = "^0.3.2"
watchdog = "^2.0.2"
pendulum = "^2.1.2"
Pillow = "^8.2.0"
ipython = "^7.23.0"
ipykernel = "^5.5.3"
nbterm = ">=0.0.7,<0.0.11"
toml = "^0.10.2"
uniplot = "^0.4.4"
numpy = "^1.20.3"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-watch = "^4.2.0"
pytest-cov = "^2.11.1"
pytest-xdist = "^2.2.1"
mypy = "^0.812"
pytest-mypy = "^0.8.1"
pytest-mock = "^3.5.1"
hypothesis = "^6.13.5"
Sphinx = "^4.0.2"
sphinx-rtd-theme = "^0.5.2"
sphinx-autobuild = "^2021.3.14"
line-profiler = "^3.2.6"

[tool.poetry.scripts]
spiel = 'spiel.main:app'

[tool.pytest.ini_options]
addopts = ['--strict-markers', '--mypy']
testpaths = ["tests", "spiel"]
norecursedirs = ["demo"]
