language: python
dist: focal
cache: pip
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy2
  - pypy3
install:
  - pip install pytest coverage coverage-python-version coveralls flake8
  - pip install -e .
script:
  - coverage run -m pytest
  - flake8 *.py
  - coverage report -m $([[ $TRAVIS_PYTHON_VERSION != pypy3 ]] && echo --fail-under=100)
after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net##mgedmin"
    on_success: change
    on_failure: always
    template:
      # ping my nick so I get a pushbullet notification on my phone
      - "mgedmin: %{repository_name} (%{branch}) build %{result}: %{build_url}"
