
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-23T19:25:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1366221b10a977aa91fb9460a2e8441616f5a4e7",
 "version": "2.0.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
