[tool.poetry]
name = "alchemista"
version = "0.3.0"
description = "Tools to convert SQLAlchemy models to Pydantic models"
license = "MIT"
authors = ["Gabriel Galli <ggabriel96@hotmail.com>"]
readme = "README.md"
repository = "https://github.com/ggabriel96/alchemista"

[tool.poetry.dependencies]
pydantic = "^1.8.1"
python = "^3.8"
SQLAlchemy = "^1.4.14"
Deprecated = "^1.2.12"

[tool.poetry.dev-dependencies]
black = "^21.5b0"
isort = "^5.8.0"
mypy = "^0.812"
pre-commit = "^2.12.1"
pylint = "^2.8.2"
pytest = "^6.2.4"
pytest-cov = "^2.11.1"
SQLAlchemy-Utc = "^0.12.0"
sqlalchemy2-stubs = "^0.0.1-alpha.10"
python-semantic-release = "^7.15.5"
commitizen = "^2.17.8"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.semantic_release]
branch = "main"
build_command = "poetry build"
commit_author = "github-actions <actions@github.com>"
major_on_zero = false
version_toml = "pyproject.toml:tool.poetry.version"
