[tool.poetry]
name = "floyd_warshall_alg"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Cycler = "0.10.0"
kiwisolver = "1.3.1"
matplotlib = "3.4.2"
numpy = "1.20.3"
pandas = "1.2.4"
Pillow = "8.2.0"
pyparsing = "2.4.7"
python-dateutil = "2.8.1"
pytz = "2021.1"
six = "1.16.0"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
floyd_alg = 'floyd_warshall_alg.simple_algorithm:main'