default:
  omc_home: "@format {env[HOME]}/.omc"
  config_dir: "@format {this.OMC_HOME}/config"
  cache_dir: "@format {this.OMC_HOME}/cache"
  bin_dir: "@format {this.OMC_HOME}/bin"
  log_dir: "@format {this.OMC_HOME}/logs"
  resource_config_dir: "@format {this.CONFIG_DIR}/resources"
  omc_completion_cache_dir: "@format {this.CACHE_DIR}/completion"
  competion_timeout: 5
  db:
    drivername: sqlite
    database: "@format {env[OMC_HOME]}/omc.db"
  
