[tool.poetry]
name = "melib"
version = "0.1.0"
description = "Machine element design teaching library"
authors = ["Gurgenci <h.gurgenci@uq.edu.au>"]
license = "LICENSE"

[tool.poetry.dependencies]
python = "^3.8"
PyLaTeX = "^1.4.1"
CoolPlot = "^0.1.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
