
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-31T03:21:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "141d686617e35f062950295941c348558c1e555c",
 "version": "1.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
