repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "11cdc8d8201091a19ff1c28f7b7c75c3691954ad"
    hooks:
      # - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hakancelik96/unimport
    rev: fdf31b7940133f0a5307a767b6485d344ac2007b
    hooks:
      - id: unimport
        args: [--remove, --include-star-import]
  - repo: https://github.com/pycqa/isort
    rev: "a4addbd54ac5a49cfb3cba5a7de4b0c0d7459246"
    hooks:
        - id: isort
          files: "pp/.*"
          args: ["--profile", "black", "--filter-files"]

  # - repo: https://github.com/asottile/reorder_python_imports
  #   rev: 2b2f0c74acdb3de316e23ceb7dd0d7945c354050
  #   hooks:
  #     - id: reorder-python-imports

  - repo: https://github.com/psf/black
    rev: "f933e8a8382e6945bf950356f6ecc4ded5617617"
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: "28aa67314e2c451002d6362c54aed6e08f4f9f19"
    hooks:
      - id: flake8
  - repo: https://github.com/kynan/nbstripout
    rev: d1e7d2662e29093b0be4056cf26cd2d449034882
    hooks:
      - id: nbstripout
        files: ".ipynb"

  # - repo: https://github.com/terrencepreilly/darglint
  #   rev: master
  #   hooks:
  #       - id: darglint
  #
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: ""
  #   hooks:
  #       - id: mypy
  #         exclude: ^(docs/|example-plugin/|tests/fixtures)
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: ""
  #   hooks:
  #       - id: pydocstyle
