version: "2"

services:
  cron_docker:
    build: "./"
    volumes:
      - /home/aniulee/datas/python_space/github/xiaoniu_cron:/home/www
    ports:
      - "5002:80"
    command: "/usr/bin/supervisord"
    environment:
      PYTHONIOENCODING: "utf-8"
      FLASK_CONFIG: "production"
    restart: always