[tool.poetry]
name = "gitlab2nextclouddeck"
version = "0.1.11"
description = ""
authors = ["Ferit Cubukcuoglu <info@yazcub.com>"]

# New attributes
license = "MIT"
readme = "README.md"
homepage = "https://yazcub.com"
repository = "https://github.com/yazcub"
keywords = ["gitlab", "nextcloud", "deck"]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
PyInquirer = "^1.0.3"
progress = "^1.5"
python-dotenv = "^0.17.1"
python-gitlab = "^2.7.1"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
black = "^21.5b1"

[tool.poetry.scripts]
gitlab2nextclouddeck = "gitlab2nextclouddeck.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
