[tool.poetry]
name = "tragic_semester_work_2"
version = "0.1.2"
description = ""
authors = ["Пётр Куркин <kurkin801@mail.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.scripts]
tragic_semester_work_2 = "tragic_semester_work_2.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
