[tool.poetry]
name = "assert_headers"
version = "1.0.0"
description = "Assert HTTP headers."
authors = ["David Ragsdale <pkgsupport@davidjragsdale.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/djragsdale/assert-headers-python"
repository = "https://github.com/djragsdale/assert-headers-python"
keywords = ["http", "https", "headers", "assert"]
include = ["LICENSE"]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[tool.poetry.scripts]
assert-headers-py = "assert_headers.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
