
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-28T14:30:49+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4a49a44aaf0ec854979898c2feca1151d6f6864",
 "version": "0.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
