from ChoateStudentHelp.ChoateStudentHelp_module import Math
from ChoateStudentHelp.ChoateStudentHelp_module import standardizedTest
from ChoateStudentHelp.ChoateStudentHelp_module import stocks
from ChoateStudentHelp.ChoateStudentHelp_module import fortune_teller
from ChoateStudentHelp.ChoateStudentHelp_module import walking_time
from ChoateStudentHelp.ChoateStudentHelp_module import visual_design