# This file is part of the django-environ-2.
#
# Copyright (C) 2021 Serghei Iakovlev <egrep@protonmail.ch>
# Copyright (C) 2013-2021 Daniele Faraglia <daniele.faraglia@gmail.com>
#
# For the full copyright and license information, please view
# the LICENSE file that was distributed with this source code.

name: Build

on:
  push:
    branches:
      - master
      - 'feature/**'
      - 'release/**'
      - 'hotfix/**'
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

  pull_request:
    branches:
      - master
      - 'v[0-9]+.[0-9]+.x'

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build and test package distribution

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip --use-feature=in-tree-build install tox tox-gh-actions

      - name: Check MANIFEST.in for completeness
        run: tox -e manifest

      - name: Build and test package
        run: tox -e build

  install-dev:
    name: Verify dev environment
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Set up Python 3.9
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.9'

      - name: Install in dev mode
        run: python -m pip install -e .[develop]

      - name: Import package
        run: python -c 'import environ; print(environ.__version__)'
