
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-27T15:09:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "0576574d178023d464f57b7c23d72d6128735ad5",
 "version": "v0.1.0a2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
