[tool.poetry]
name = "stefaneicher"
version = "0.1.0"
description = ""
authors = ["Stefan Eicher <stefan.eicher@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
conan = "^1.36.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mumoco = "^0.2.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
