
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-25T18:04:10-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "62934b98d722604274978db32143f09676f7fc88",
 "version": "0.14.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
