
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-26T08:42:55+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "51d234408d188c622570f5c6942c219846457e74",
 "version": "2478"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
