[tool.poetry]
name = "wj_credentials"
version = "0.1.1"
description = "Whale&Jaguar Libary - Credentials"
authors = ["Sebastian Franco <jsfranco@whaleandjaguar.co>"]
license = "GNU3"

[tool.poetry.dependencies]
python = ">3.6.1,<4.0"
boto3 = "1.14.52"

[tool.poetry.dev-dependencies]
pylint = "2.4.4"
colorama = "0.4.3"
gitlint = "0.15.1"
autopep8 = "1.5.6"
pyflakes = "2.3.1"
yapf = "0.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.semantic_release]
version_variable = [
  "wj_credentials/__init__.py:__version__",
  "pyproject.toml:version"
]

branch = "master"
upload_to_pypi = true
upload_to_release = true
build_command = "poetry build"