
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-25T06:18:39+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "3723c1f62e61c6e9cf6c9a318f085ead2fbc7394",
 "version": "2.6.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
