[tool.isort]
profile = "black"

[tool.poetry]
name = "tsrc"
version = "2.3.0"
description = "Manage groups of git repositories"
authors = ["Dimitri Merejkowsky <dimitri@dmerej.info>"]
readme = "README.rst"
license = "BSD-3-Clause"
repository = "https://github.com/dmerejkowsky/tsrc"
documentation = "https://dmerejkowsky.github.io/tsrc"

[tool.poetry.urls]
Changelog = "https://dmerejkowsky.github.io/tsrc/changelog/"
Issues = "https://github.com/dmerejkowsky/tsrc/issues"

[tool.poetry.dependencies]
# Note: keep this in sync with .github/workflows/tests.yml
python = "^3.6.2"

attrs = "^19.3.0"
cli-ui = "^0.11.0"
colored_traceback = "^0.3.0"
"ruamel.yaml" = "^0.16.7"
schema = "^0.7.1"
tabulate = "^0.8.6"
unidecode = "^1.1.1"

[tool.poetry.dev-dependencies]
# Tests
coverage = "^5.1"
pytest = "^6.0.1"
pytest-cov = "^2.8.1"
pytest-xdist = "^1.32.0"
pygit2 = "^1.2.0"  # for GitSever test helpers
mock = "^3.0.5"

# Linters
black = "21.5b0"
flake8 = "3.7.8"
flake8-comprehensions = "1.4.1"
flake8-bugbear = "^21.4.3"
pep8-naming = "^0.11.1"
isort = "^5.6.4"
mypy = "0.790"

# Docs
mkdocs = "1.0.4"

# Deps scanning
safety = "^1.9.0"
invoke = "^1.5.0"

[tool.poetry.scripts]
tsrc = "tsrc.cli.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
