[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "Cython>=0.28.5",
    "setuptools_scm[toml]>=3.4",
    "oldest-supported-numpy"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "soxr/version.py"
