language: python

jobs:
  include:
    - name: "py3.6"
      python: 3.6

    - name: "py3.7"
      python: 3.7

    - name: "py3.8"
      python: 3.8
    
    - name: "py3.9"
      python: 3.9

install:
  - pip install pytest-cov
  - pip install coveralls
  - pip install -e .

script:
  - pytest --cov src -s
    
after_success:
  - coverage report -m
  - coveralls
  