
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-27T11:02:35-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1a6811cd329ee2835909c2203c08e5f9bce9a183",
 "version": "4.5.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
