
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-27T17:50:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "aa49efff4d7b8e4c0d5b59373e75c72519b6e8a5",
 "version": "1.0.0.post.dev24"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
