[tool.poetry]
name = "condorcet"
version = "0.1.0"
description = ""
authors = ["Mfon Eti-mfon <mfonetimfon@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pytest-mock = "^3.6.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
