
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-24T14:05:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "aef1acb0bad59e0e020f094677315fe5a1ce0af9",
 "version": "2475"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
