"""
    Portal OpenAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""

import pathlib
import os

from setuptools import setup, find_packages  # noqa: H301

NAME = "portal-openapi-client"
VERSION = "0.2.5"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = [
  "urllib3 >= 1.25.3",
  "python-dateutil",
]

path = os.path.dirname(__file__)
parent: pathlib.Path = pathlib.Path(__file__).parent
print(f"Path: {path}")

# Get the long description from the README file

readme = os.path.join(path, "README.md")
print(f"Readme: {readme}")

with open(readme) as f:
    long_description = f.readlines()

for doc in os.listdir(os.path.join(path, "docs")):
    doc_path = os.path.join(path, "docs", doc)
    print(f"File: {doc_path}")
    with open(doc_path) as f:
        long_description = long_description + ["\n\n"] + f.readlines()

release_notes = os.path.join(path, "RELEASE_NOTES.md")


with open(release_notes) as f:
    long_description = long_description + ["\n\n"] + f.readlines()

setup(
    name=NAME,
    version=VERSION,
    description="Portal OpenAPI",
    author="OpenAPI Generator community",
    author_email="team@openapitools.org",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "Portal OpenAPI"],
    python_requires=">=3.6",
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description="".join(long_description),
    long_description_content_type="text/markdown",
)
