[tool.poetry]
name = "mugmoment"
version = "0.2.1"
description = "Library to download chat logs from twitch VODs"
authors = ["Ave <ave@ave.zone>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/a/mugmoment"

[tool.poetry.dependencies]
python = "^3.6"
httpx = "^0.17.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
