
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-27T01:36:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c37affb3fb630fcdcf4383ab5c4bfdd5155fd801",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
