
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-25T15:34:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c15ecb85e155896a8c28e6c7218416b9d398c8d1",
 "version": "2021.05.25post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
