[tool.poetry]
name = "aiogram-metrics"
version = "0.0.2"
description = "Message metrics exporter for aiogram framework"
authors = ["Benyamin Ginzburg <benyomin.94@gmail.com>"]
license = "GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.7"
aiogram = "^2.13"
aiopg = "^1.2.1"
betterlogging = "^0.0.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
