[tool.poetry]
name = "poc_publish"
version = "0.1.0"
description = ""
authors = ["Gláuber Brennon <glauberbrennon@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pyfiglet = "^0.8.post1"
termcolor = "^1.1.0"
black = "^21.5b1"
mypy = "^0.812"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
