# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intentionet/bfe/proto/datamodel/config_text.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from intentionet.bfe.proto.datamodel import range_pb2 as intentionet_dot_bfe_dot_proto_dot_datamodel_dot_range__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='intentionet/bfe/proto/datamodel/config_text.proto',
  package='com.intentionet.datamodel',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1intentionet/bfe/proto/datamodel/config_text.proto\x12\x19\x63om.intentionet.datamodel\x1a+intentionet/bfe/proto/datamodel/range.proto\"c\n\tFileLines\x12\x1b\n\tfile_name\x18\x01 \x01(\tR\x08\x66ileName\x12\x39\n\x05lines\x18\x02 \x03(\x0b\x32#.com.intentionet.datamodel.IntRangeR\x05linesB\x02P\x01\x62\x06proto3'
  ,
  dependencies=[intentionet_dot_bfe_dot_proto_dot_datamodel_dot_range__pb2.DESCRIPTOR,])




_FILELINES = _descriptor.Descriptor(
  name='FileLines',
  full_name='com.intentionet.datamodel.FileLines',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='com.intentionet.datamodel.FileLines.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='fileName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lines', full_name='com.intentionet.datamodel.FileLines.lines', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='lines', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=224,
)

_FILELINES.fields_by_name['lines'].message_type = intentionet_dot_bfe_dot_proto_dot_datamodel_dot_range__pb2._INTRANGE
DESCRIPTOR.message_types_by_name['FileLines'] = _FILELINES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileLines = _reflection.GeneratedProtocolMessageType('FileLines', (_message.Message,), {
  'DESCRIPTOR' : _FILELINES,
  '__module__' : 'intentionet.bfe.proto.datamodel.config_text_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.datamodel.FileLines)
  })
_sym_db.RegisterMessage(FileLines)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
