[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "opaclient"
author = "Yash Tewari"
author-email = "yashtewari1996@gmail.com"
home-page = "https://docs.build.security/"
classifiers = [ "License :: OSI Approved :: MIT License",]
description-file = "README.md"

