#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['histomics_stream']

package_data = \
{'': ['*'], 'histomics_stream': ['ds/*', 'dsm/*']}

install_requires = \
['fsspec',
 'h5py',
 'imagecodecs',
 'itk',
 'napari-lazy-openslide',
 'numcodecs',
 'numpy',
 'openslide-python',
 'Pillow',
 'tensorflow-gpu',
 'tifffile',
 'zarr']

setup(name='histomics_stream',
      version='1.1.0',
      description='Whole-slide image streamer for TensorFlow.',
      author='Lee Newberg',
      author_email='lee.newberg@kitware.com',
      url='https://github.com/DigitalSlideArchive/histomics_stream',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
