
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-30T18:45:32-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1758a238efbc94a7ea5fad77c184ccae0c65735",
 "version": "1.0.61"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
