
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-25T15:44:22+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "72709b44b26ccd1d914972560549a81e45978dda",
 "version": "0.8.5b0.dev202105260741"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
