[tool.poetry]
name = "helen_db"
version = "0.1.1"
description = ""
authors = ["Andrew"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
