[tool.poetry]
name = "informathion"
version = "0.2.3"
description = "Framework for Minimizing Opportunity Loss"
authors = ["migueltorrescosta <miguelptcosta1995@gmail.com>"]
license = "AGPL-3.0-only"
readme = "README.rst"
repository = "https://github.com/migueltorrescosta/informathion"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.20.3"
pandas = "^1.2.4"
seaborn = "^0.11.1"
matplotlib = "^3.4.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
