
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5fb1a6533f773805f9e17dcf1d701e0a0b1903ab",
 "version": "7.6.2pre7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
