# SPDX-FileCopyrightText: 2017 Scott Shawcroft, written for Adafruit Industries
#
# SPDX-License-Identifier: MIT

name: Build CI

on: [pull_request, push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
#    - name: Translate Repo Name For Build Tools filename_prefix
#      id: repo-name
#      run: |
#        echo ::set-output name=repo-name::$(
#        echo ${{ github.repository }} |
#        awk -F '\/' '{ print tolower($2) }' |
#        tr '_' '-'
#        )
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Versions
      run: |
        python3 --version
    - name: Checkout Current Repo
      uses: actions/checkout@v2
    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt-get install libudev-dev libusb-1.0
        sudo apt-get install -y gettext
        pip install -r requirements.txt
#    - name: Checkout tools repo
#      uses: actions/checkout@v2
#      with:
#        repository: adafruit/actions-ci-circuitpython-libs
#        path: actions-ci
#    - name: Install dependencies
#      # (e.g. - apt-get: gettext, etc; pip: circuitpython-build-tools, requirements.txt; etc.)
#      run: |
#        source actions-ci/install.sh
    - name: Library version
      run: git describe --dirty --always --tags
#    - name: Setup problem matchers
#      uses: adafruit/circuitpython-action-library-ci-problem-matchers@v1
#    - name: Build assets
#      run: circuitpython-build-bundles --filename_prefix ${{ steps.repo-name.outputs.repo-name }} --library_location .
#    - name: Archive bundles
#      uses: actions/upload-artifact@v2
#      with:
#        name: bundles
#        path: ${{ github.workspace }}/bundles/
    - name: Install package locally
      run: pip install -e .
    - name: Test building single package
      run: |
        git clone https://github.com/adafruit/Adafruit_CircuitPython_FeatherWing.git
        cd Adafruit_CircuitPython_FeatherWing
        circuitpython-build-bundles --filename_prefix test-single --library_location .
    - name: Test building bundle
      run: |
        # Use the community bundle because it's smaller and faster
        git clone --recurse-submodules https://github.com/adafruit/CircuitPython_Community_Bundle.git
        cd CircuitPython_Community_Bundle
        circuitpython-build-bundles --filename_prefix test-bundle --library_location libraries --library_depth 2
    - name: Build Python package
      run: |
        pip install --upgrade setuptools wheel twine readme_renderer testresources
        python setup.py sdist
        twine check dist/*
