name: Workflow CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  runsnkmk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: setup-conda
        uses: s-weigand/setup-conda@v1.0.5
        with:
          activate-conda: true
          update-conda: true
          conda-channels: "defaults,conda-forge,bioconda,kdm801"
      
      - name: Install conda deps
        run: |
          conda install mamba
          pip install -e .
      
      - name: Run snakemake
        run: |
          pushd example
          acanthophis-init --force
          mamba env update -n base -f environment.yml
          snakemake --snakefile Snakefile.generate-rawdata -j 4 --use-conda --conda-frontend mamba
          snakemake --snakefile Snakefile -j 4 --use-conda --conda-frontend mamba
          popd

