[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "icerok_server"
author = "Juan Gonzalez (Obijuan)"
author-email = "obijuan.cube@gmail.com"
home-page = "https://github.com/FPGAwars/icerok-server-python"
classifiers = [ "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",]
description-file = "README.md"
requires-python = ">=3.7"
requires = [
    "pyserial >= 3.5"
]

[tool.flit.scripts]
icerok-server = "icerok_server.main:_main"



