# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SDMS_Anon.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import SDMS_pb2 as SDMS__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SDMS_Anon.proto',
  package='SDMS.Anon',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0fSDMS_Anon.proto\x12\tSDMS.Anon\x1a\nSDMS.proto\"\n\n\x08\x41\x63kReply\"?\n\tNackReply\x12!\n\x08\x65rr_code\x18\x01 \x02(\x0e\x32\x0f.SDMS.ErrorCode\x12\x0f\n\x07\x65rr_msg\x18\x02 \x01(\t\"\x10\n\x0eVersionRequest\"e\n\x0cVersionReply\x12\r\n\x05major\x18\x01 \x02(\r\x12\x12\n\nmapi_major\x18\x02 \x02(\r\x12\x12\n\nmapi_minor\x18\x03 \x02(\r\x12\x0e\n\x06server\x18\x04 \x02(\r\x12\x0e\n\x06\x63lient\x18\x05 \x02(\r\"\x0f\n\rStatusRequest\"2\n\x0bStatusReply\x12#\n\x06status\x18\x01 \x02(\x0e\x32\x13.SDMS.ServiceStatus\"\x13\n\x11ServerInfoRequest\"=\n\x0fServerInfoReply\x12\x0f\n\x07\x63ountry\x18\x01 \x02(\t\x12\x0b\n\x03org\x18\x02 \x02(\t\x12\x0c\n\x04unit\x18\x03 \x02(\t\"\x16\n\x14GetAuthStatusRequest\",\n\x0f\x41uthStatusReply\x12\x0c\n\x04\x61uth\x18\x01 \x02(\x08\x12\x0b\n\x03uid\x18\x02 \x01(\t\">\n\x1d\x41uthenticateByPasswordRequest\x12\x0b\n\x03uid\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"+\n\x1a\x41uthenticateByTokenRequest\x12\r\n\x05token\x18\x01 \x02(\t\".\n\x0e\x44OIViewRequest\x12\x0b\n\x03\x64oi\x18\x01 \x02(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\x08\"/\n\x0fUserViewRequest\x12\x0b\n\x03uid\x18\x01 \x02(\t\x12\x0f\n\x07\x64\x65tails\x18\x02 \x01(\x08\"[\n\rUserDataReply\x12\x1c\n\x04user\x18\x01 \x03(\x0b\x32\x0e.SDMS.UserData\x12\x0e\n\x06offset\x18\x02 \x01(\r\x12\r\n\x05\x63ount\x18\x03 \x01(\r\x12\r\n\x05total\x18\x04 \x01(\r*\x12\n\x08Protocol\x12\x06\n\x02ID\x10\x01')
  ,
  dependencies=[SDMS__pb2.DESCRIPTOR,])

_PROTOCOL = _descriptor.EnumDescriptor(
  name='Protocol',
  full_name='SDMS.Anon.Protocol',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID', index=0, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=762,
  serialized_end=780,
)
_sym_db.RegisterEnumDescriptor(_PROTOCOL)

Protocol = enum_type_wrapper.EnumTypeWrapper(_PROTOCOL)
ID = 1



_ACKREPLY = _descriptor.Descriptor(
  name='AckReply',
  full_name='SDMS.Anon.AckReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=52,
)


_NACKREPLY = _descriptor.Descriptor(
  name='NackReply',
  full_name='SDMS.Anon.NackReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='SDMS.Anon.NackReply.err_code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='err_msg', full_name='SDMS.Anon.NackReply.err_msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=117,
)


_VERSIONREQUEST = _descriptor.Descriptor(
  name='VersionRequest',
  full_name='SDMS.Anon.VersionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=135,
)


_VERSIONREPLY = _descriptor.Descriptor(
  name='VersionReply',
  full_name='SDMS.Anon.VersionReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='major', full_name='SDMS.Anon.VersionReply.major', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapi_major', full_name='SDMS.Anon.VersionReply.mapi_major', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mapi_minor', full_name='SDMS.Anon.VersionReply.mapi_minor', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='server', full_name='SDMS.Anon.VersionReply.server', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client', full_name='SDMS.Anon.VersionReply.client', index=4,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=238,
)


_STATUSREQUEST = _descriptor.Descriptor(
  name='StatusRequest',
  full_name='SDMS.Anon.StatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=255,
)


_STATUSREPLY = _descriptor.Descriptor(
  name='StatusReply',
  full_name='SDMS.Anon.StatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SDMS.Anon.StatusReply.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=257,
  serialized_end=307,
)


_SERVERINFOREQUEST = _descriptor.Descriptor(
  name='ServerInfoRequest',
  full_name='SDMS.Anon.ServerInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=328,
)


_SERVERINFOREPLY = _descriptor.Descriptor(
  name='ServerInfoReply',
  full_name='SDMS.Anon.ServerInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='country', full_name='SDMS.Anon.ServerInfoReply.country', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='org', full_name='SDMS.Anon.ServerInfoReply.org', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unit', full_name='SDMS.Anon.ServerInfoReply.unit', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=391,
)


_GETAUTHSTATUSREQUEST = _descriptor.Descriptor(
  name='GetAuthStatusRequest',
  full_name='SDMS.Anon.GetAuthStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=415,
)


_AUTHSTATUSREPLY = _descriptor.Descriptor(
  name='AuthStatusReply',
  full_name='SDMS.Anon.AuthStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='auth', full_name='SDMS.Anon.AuthStatusReply.auth', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uid', full_name='SDMS.Anon.AuthStatusReply.uid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=417,
  serialized_end=461,
)


_AUTHENTICATEBYPASSWORDREQUEST = _descriptor.Descriptor(
  name='AuthenticateByPasswordRequest',
  full_name='SDMS.Anon.AuthenticateByPasswordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='SDMS.Anon.AuthenticateByPasswordRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='SDMS.Anon.AuthenticateByPasswordRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=463,
  serialized_end=525,
)


_AUTHENTICATEBYTOKENREQUEST = _descriptor.Descriptor(
  name='AuthenticateByTokenRequest',
  full_name='SDMS.Anon.AuthenticateByTokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='SDMS.Anon.AuthenticateByTokenRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=570,
)


_DOIVIEWREQUEST = _descriptor.Descriptor(
  name='DOIViewRequest',
  full_name='SDMS.Anon.DOIViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='doi', full_name='SDMS.Anon.DOIViewRequest.doi', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='SDMS.Anon.DOIViewRequest.details', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=572,
  serialized_end=618,
)


_USERVIEWREQUEST = _descriptor.Descriptor(
  name='UserViewRequest',
  full_name='SDMS.Anon.UserViewRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='SDMS.Anon.UserViewRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='details', full_name='SDMS.Anon.UserViewRequest.details', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=667,
)


_USERDATAREPLY = _descriptor.Descriptor(
  name='UserDataReply',
  full_name='SDMS.Anon.UserDataReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='SDMS.Anon.UserDataReply.user', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='SDMS.Anon.UserDataReply.offset', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='count', full_name='SDMS.Anon.UserDataReply.count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total', full_name='SDMS.Anon.UserDataReply.total', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=669,
  serialized_end=760,
)

_NACKREPLY.fields_by_name['err_code'].enum_type = SDMS__pb2._ERRORCODE
_STATUSREPLY.fields_by_name['status'].enum_type = SDMS__pb2._SERVICESTATUS
_USERDATAREPLY.fields_by_name['user'].message_type = SDMS__pb2._USERDATA
DESCRIPTOR.message_types_by_name['AckReply'] = _ACKREPLY
DESCRIPTOR.message_types_by_name['NackReply'] = _NACKREPLY
DESCRIPTOR.message_types_by_name['VersionRequest'] = _VERSIONREQUEST
DESCRIPTOR.message_types_by_name['VersionReply'] = _VERSIONREPLY
DESCRIPTOR.message_types_by_name['StatusRequest'] = _STATUSREQUEST
DESCRIPTOR.message_types_by_name['StatusReply'] = _STATUSREPLY
DESCRIPTOR.message_types_by_name['ServerInfoRequest'] = _SERVERINFOREQUEST
DESCRIPTOR.message_types_by_name['ServerInfoReply'] = _SERVERINFOREPLY
DESCRIPTOR.message_types_by_name['GetAuthStatusRequest'] = _GETAUTHSTATUSREQUEST
DESCRIPTOR.message_types_by_name['AuthStatusReply'] = _AUTHSTATUSREPLY
DESCRIPTOR.message_types_by_name['AuthenticateByPasswordRequest'] = _AUTHENTICATEBYPASSWORDREQUEST
DESCRIPTOR.message_types_by_name['AuthenticateByTokenRequest'] = _AUTHENTICATEBYTOKENREQUEST
DESCRIPTOR.message_types_by_name['DOIViewRequest'] = _DOIVIEWREQUEST
DESCRIPTOR.message_types_by_name['UserViewRequest'] = _USERVIEWREQUEST
DESCRIPTOR.message_types_by_name['UserDataReply'] = _USERDATAREPLY
DESCRIPTOR.enum_types_by_name['Protocol'] = _PROTOCOL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AckReply = _reflection.GeneratedProtocolMessageType('AckReply', (_message.Message,), dict(
  DESCRIPTOR = _ACKREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.AckReply)
  ))
_sym_db.RegisterMessage(AckReply)

NackReply = _reflection.GeneratedProtocolMessageType('NackReply', (_message.Message,), dict(
  DESCRIPTOR = _NACKREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.NackReply)
  ))
_sym_db.RegisterMessage(NackReply)

VersionRequest = _reflection.GeneratedProtocolMessageType('VersionRequest', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.VersionRequest)
  ))
_sym_db.RegisterMessage(VersionRequest)

VersionReply = _reflection.GeneratedProtocolMessageType('VersionReply', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.VersionReply)
  ))
_sym_db.RegisterMessage(VersionReply)

StatusRequest = _reflection.GeneratedProtocolMessageType('StatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.StatusRequest)
  ))
_sym_db.RegisterMessage(StatusRequest)

StatusReply = _reflection.GeneratedProtocolMessageType('StatusReply', (_message.Message,), dict(
  DESCRIPTOR = _STATUSREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.StatusReply)
  ))
_sym_db.RegisterMessage(StatusReply)

ServerInfoRequest = _reflection.GeneratedProtocolMessageType('ServerInfoRequest', (_message.Message,), dict(
  DESCRIPTOR = _SERVERINFOREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.ServerInfoRequest)
  ))
_sym_db.RegisterMessage(ServerInfoRequest)

ServerInfoReply = _reflection.GeneratedProtocolMessageType('ServerInfoReply', (_message.Message,), dict(
  DESCRIPTOR = _SERVERINFOREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.ServerInfoReply)
  ))
_sym_db.RegisterMessage(ServerInfoReply)

GetAuthStatusRequest = _reflection.GeneratedProtocolMessageType('GetAuthStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETAUTHSTATUSREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.GetAuthStatusRequest)
  ))
_sym_db.RegisterMessage(GetAuthStatusRequest)

AuthStatusReply = _reflection.GeneratedProtocolMessageType('AuthStatusReply', (_message.Message,), dict(
  DESCRIPTOR = _AUTHSTATUSREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.AuthStatusReply)
  ))
_sym_db.RegisterMessage(AuthStatusReply)

AuthenticateByPasswordRequest = _reflection.GeneratedProtocolMessageType('AuthenticateByPasswordRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATEBYPASSWORDREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.AuthenticateByPasswordRequest)
  ))
_sym_db.RegisterMessage(AuthenticateByPasswordRequest)

AuthenticateByTokenRequest = _reflection.GeneratedProtocolMessageType('AuthenticateByTokenRequest', (_message.Message,), dict(
  DESCRIPTOR = _AUTHENTICATEBYTOKENREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.AuthenticateByTokenRequest)
  ))
_sym_db.RegisterMessage(AuthenticateByTokenRequest)

DOIViewRequest = _reflection.GeneratedProtocolMessageType('DOIViewRequest', (_message.Message,), dict(
  DESCRIPTOR = _DOIVIEWREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.DOIViewRequest)
  ))
_sym_db.RegisterMessage(DOIViewRequest)

UserViewRequest = _reflection.GeneratedProtocolMessageType('UserViewRequest', (_message.Message,), dict(
  DESCRIPTOR = _USERVIEWREQUEST,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.UserViewRequest)
  ))
_sym_db.RegisterMessage(UserViewRequest)

UserDataReply = _reflection.GeneratedProtocolMessageType('UserDataReply', (_message.Message,), dict(
  DESCRIPTOR = _USERDATAREPLY,
  __module__ = 'SDMS_Anon_pb2'
  # @@protoc_insertion_point(class_scope:SDMS.Anon.UserDataReply)
  ))
_sym_db.RegisterMessage(UserDataReply)


# @@protoc_insertion_point(module_scope)

_msg_name_to_type = {
    'AckReply' : 256,
    'NackReply' : 257,
    'VersionRequest' : 258,
    'VersionReply' : 259,
    'StatusRequest' : 260,
    'StatusReply' : 261,
    'ServerInfoRequest' : 262,
    'ServerInfoReply' : 263,
    'GetAuthStatusRequest' : 264,
    'AuthStatusReply' : 265,
    'AuthenticateByPasswordRequest' : 266,
    'AuthenticateByTokenRequest' : 267,
    'DOIViewRequest' : 268,
    'UserViewRequest' : 269,
    'UserDataReply' : 270
}

_msg_type_to_name = {
    256 : 'AckReply',
    257 : 'NackReply',
    258 : 'VersionRequest',
    259 : 'VersionReply',
    260 : 'StatusRequest',
    261 : 'StatusReply',
    262 : 'ServerInfoRequest',
    263 : 'ServerInfoReply',
    264 : 'GetAuthStatusRequest',
    265 : 'AuthStatusReply',
    266 : 'AuthenticateByPasswordRequest',
    267 : 'AuthenticateByTokenRequest',
    268 : 'DOIViewRequest',
    269 : 'UserViewRequest',
    270 : 'UserDataReply'
}
