# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Version.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Version.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\rVersion.proto*d\n\x07Version\x12\r\n\tVER_MAJOR\x10\x01\x12\x12\n\x0eVER_MAPI_MAJOR\x10\x02\x12\x12\n\x0eVER_MAPI_MINOR\x10\x00\x12\x0e\n\nVER_SERVER\x10\x04\x12\x0e\n\nVER_CLIENT\x10\x04\x1a\x02\x10\x01')
)

_VERSION = _descriptor.EnumDescriptor(
  name='Version',
  full_name='Version',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VER_MAJOR', index=0, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_MAPI_MAJOR', index=1, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_MAPI_MINOR', index=2, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_SERVER', index=3, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VER_CLIENT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=_b('\020\001'),
  serialized_start=17,
  serialized_end=117,
)
_sym_db.RegisterEnumDescriptor(_VERSION)

Version = enum_type_wrapper.EnumTypeWrapper(_VERSION)
VER_MAJOR = 1
VER_MAPI_MAJOR = 2
VER_MAPI_MINOR = 0
VER_SERVER = 4
VER_CLIENT = 4


DESCRIPTOR.enum_types_by_name['Version'] = _VERSION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_VERSION._options = None
# @@protoc_insertion_point(module_scope)
