image: continuumio/miniconda3:latest

before_script:
  - conda install mamba -c conda-forge
  - mamba env update -n fine --file=requirements.yml
  - mamba env update -n fine --file=requirements_dev.yml
  - mamba info --envs
  - source activate fine
  - python -m pip install -e .

test-code:
  stage: test
  script:
    - python -m pytest --cov=FINE test/

test-notebooks:
  stage: test
  script:
    # Run nbval to test all notebooks in examples folder
    #   and show 20 longest cell executing durations
    # With 'nbval-lax', notebooks are only tested for execution errors
    # Cells tagged 'nbval-check-output' are checked for consistent output
    # Cells tagged 'nbval-skip' are skipped
    - python -m pytest --nbval-lax --current-env --durations=20 examples/
  # Only test examples notebooks for branches master, develop and 47-test-notebooks
  only:
    refs:
      - master
      - develop
      - 161-exclude-cells-with-gpd-from-testing