[tool.poetry]
name = "kraken-class"
version = "0.1.0"
description = ""
authors = ["Replit user <replituser@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
kraken-db = "^0.0.10"
kraken-cache = "^0.0.3"
pysces = "^0.9.8"
kraken-record = "^0.0.4"
kraken-html = "^0.0.18"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
