
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-31T20:49:52+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d859250dd90f48519d5b8e5e6ead1a3e60e7e48",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
