#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['namely', 'namely.resources']

package_data = \
{'': ['*']}

install_requires = \
['requests==2.25.1', 'retrying==1.3.3']

setup(name='namely',
      version='0.0.2',
      description='Namely Python Client',
      author='VadymKhodak',
      author_email='vaddimart@gmail.com',
      url='https://github.com/VadymKhodak/namely',
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      python_requires='>=3.7',
     )
