[build-system]
requires = ['pip', 'setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-common<=2.8.0.dev20210522', 'dune-geometry<=2.8.0.dev20210522', 'dune-grid<=2.8.0.dev20210522']
build-backend = 'setuptools.build_meta'
