[tool.poetry]
name = "qset-tslib"
version = "0.1.1"
description = ""
authors = ["Arsenii Kadaner <arseniikadaner@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
pandas = "^1.2.3"
numpy = "^1.20.1"
statsmodels = "^0.12.2"
scikit-learn = "^0.23.1"
scipy = "^1.6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
