[tool.poetry]
name = "csv-reconcile-levenshtein"
version = "0.1.5"
description = "Levenshtein distance scoring plugin for csv-reconcile"
authors = ["Douglas Mennella <trx2358-pypi@yahoo.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/gitonthescene/csv-reconcile-levenshtein"
keywords = ["OpenRefine",
            "reconcile",
            "fuzzy search",
            "Levenshtein"]

[tool.poetry.dependencies]
python = "^3.7"
python-Levenshtein = "^0.12.2"
csv-reconcile = "^0.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[tool.poetry.plugins."csv_reconcile.scorers"]
"levenshtein" = "csv_reconcile_levenshtein"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
