
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-25T05:20:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2265219aafcb4330e406146b899a6234f7b95f19",
 "version": "0.7.0.post.dev138"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
