[tool.poetry]
name = "dynbike_functions"
version = "0.1.4"
description = "A small package with collection of useful functions for the Dynamic Bike"
authors = ["pomkos <albeithome@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
