[tool.poetry]
name = "pyrediscore"
version = "0.2.5"
description = "Low-level decorators for redis instance I/O operations"
authors = ["glaunay <pitooon@gmail.com>"]
license = "GPL"
classifiers = [ 
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Scientific/Engineering :: Bio-Informatics',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3 :: Only',
    ]
repository = "https://github.com/MMSB-MOBI/pyrediscore"

[tool.poetry.dependencies]
python = "^3.7"
decorator = "^5.0.9"
redis = "^3.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
