[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "logjsonfmt"
author = "Bin Wen"
author-email = "caowb@pillar-biosciences.com"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
description-file = "README.md"
[tool.isort]
profile = "black"
known_third_party = ["logging", "json", "formatter"]
[tool.flit.sdist]
exclude = ["__pycache__"]
