
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-31T12:39:05+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3fc8b2b37b9ed7c267a0dddd8cd8464615cea1f",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
