[tool.poetry]
name = "ralfsnbutils"
version = "0.1.0"
description = ""
authors = ["rschmidtner <RSchmidtner@NewYorker.de>"]

[tool.poetry.dependencies]
python = "^3.6"
pandas = "~0.23"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
