[tool.poetry]
name = "poetry-version-plugin"
version = "0.1.0"
description = ""
authors = ["Sebastián Ramírez <tiangolo@gmail.com>"]
readme = "README.md"
packages = [{include = "poetry_version_plugin"}]

[tool.poetry.dependencies]
python = "^3.6.2"
poetry = "^1.2.0a"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
mypy = "^0.812"
flake8 = "^3.9.2"
black = "^21.5-beta.1"

[tool.poetry.plugins."poetry.plugin"]
init-version = "poetry_version_plugin.plugin:InitVersion"
git-tag-version = "poetry_version_plugin.plugin:GitTagVersion"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
