
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-31T17:42:42-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "f261c10df8fa2c8cd2d61eb21d2c3db0a19b71ad",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
