
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-27T16:20:46+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "58601b12cb36b297fb22a79e56b32cac4f412676",
 "version": "0.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
