
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-25T12:44:43+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8676827c66c81dccd6839bba111b7084f607aad",
 "version": "2477"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
