
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-26T13:13:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec610ba174ffec629de2a1a479e38159e9b9c08a",
 "version": "2480"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
