# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import simulation_node_pb2 as simulation__node__pb2


class SimulationNodeStub(object):
    """The SimulationNode service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/simulation_node_package.SimulationNode/Ping',
                request_serializer=simulation__node__pb2.PingRequest.SerializeToString,
                response_deserializer=simulation__node__pb2.PingResponse.FromString,
                )
        self.IsReady = channel.unary_unary(
                '/simulation_node_package.SimulationNode/IsReady',
                request_serializer=simulation__node__pb2.IsReadyRequest.SerializeToString,
                response_deserializer=simulation__node__pb2.IsReadyResponse.FromString,
                )


class SimulationNodeServicer(object):
    """The SimulationNode service definition.
    """

    def Ping(self, request, context):
        """Verifies responsiveness
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsReady(self, request, context):
        """Verifies readyness
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimulationNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=simulation__node__pb2.PingRequest.FromString,
                    response_serializer=simulation__node__pb2.PingResponse.SerializeToString,
            ),
            'IsReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsReady,
                    request_deserializer=simulation__node__pb2.IsReadyRequest.FromString,
                    response_serializer=simulation__node__pb2.IsReadyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simulation_node_package.SimulationNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimulationNode(object):
    """The SimulationNode service definition.
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation_node_package.SimulationNode/Ping',
            simulation__node__pb2.PingRequest.SerializeToString,
            simulation__node__pb2.PingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simulation_node_package.SimulationNode/IsReady',
            simulation__node__pb2.IsReadyRequest.SerializeToString,
            simulation__node__pb2.IsReadyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
