# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: intentionet/bfe/proto/assertions/reference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from intentionet.bfe.proto.datamodel import config_text_pb2 as intentionet_dot_bfe_dot_proto_dot_datamodel_dot_config__text__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='intentionet/bfe/proto/assertions/reference.proto',
  package='com.intentionet.bfe.assertions',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n0intentionet/bfe/proto/assertions/reference.proto\x12\x1e\x63om.intentionet.bfe.assertions\x1a\x31intentionet/bfe/proto/datamodel/config_text.proto\"\"\n UndefinedReferenceAssertionInput\"\x91\x06\n!UndefinedReferenceAssertionResult\x12h\n\tviolators\x18\x01 \x03(\x0b\x32J.com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.ViolatorR\tviolators\x1a\xa9\x03\n\x08Violator\x12\x63\n\x13undefined_reference\x18\x01 \x01(\x0b\x32\x32.com.intentionet.bfe.assertions.StructureReferenceR\x12undefinedReference\x12\x9d\x01\n\x1cincompatible_type_structures\x18\x03 \x03(\x0b\x32[.com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.IncompatibleTypeStructureR\x1aincompatibleTypeStructures\x12\x97\x01\n\x1asimilarly_named_structures\x18\x04 \x03(\x0b\x32Y.com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.SimilarlyNamedStructureR\x18similarlyNamedStructures\x1ak\n\x19IncompatibleTypeStructure\x12N\n\tstructure\x18\x01 \x01(\x0b\x32\x30.com.intentionet.bfe.assertions.DefinedStructureR\tstructure\x1ai\n\x17SimilarlyNamedStructure\x12N\n\tstructure\x18\x01 \x01(\x0b\x32\x30.com.intentionet.bfe.assertions.DefinedStructureR\tstructure\"\xcc\x01\n\x12StructureReference\x12%\n\x0ereference_name\x18\x01 \x01(\tR\rreferenceName\x12%\n\x0estructure_type\x18\x02 \x01(\tR\rstructureType\x12#\n\rusage_context\x18\x03 \x01(\tR\x0cusageContext\x12\x43\n\nfile_lines\x18\x04 \x01(\x0b\x32$.com.intentionet.datamodel.FileLinesR\tfileLines\"\xa5\x01\n\x10\x44\x65\x66inedStructure\x12%\n\x0estructure_name\x18\x01 \x01(\tR\rstructureName\x12%\n\x0estructure_type\x18\x02 \x01(\tR\rstructureType\x12\x43\n\nfile_lines\x18\x03 \x03(\x0b\x32$.com.intentionet.datamodel.FileLinesR\tfileLinesb\x06proto3'
  ,
  dependencies=[intentionet_dot_bfe_dot_proto_dot_datamodel_dot_config__text__pb2.DESCRIPTOR,])




_UNDEFINEDREFERENCEASSERTIONINPUT = _descriptor.Descriptor(
  name='UndefinedReferenceAssertionInput',
  full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=169,
)


_UNDEFINEDREFERENCEASSERTIONRESULT_VIOLATOR = _descriptor.Descriptor(
  name='Violator',
  full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.Violator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='undefined_reference', full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.Violator.undefined_reference', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='undefinedReference', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='incompatible_type_structures', full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.Violator.incompatible_type_structures', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='incompatibleTypeStructures', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='similarly_named_structures', full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.Violator.similarly_named_structures', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='similarlyNamedStructures', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=741,
)

_UNDEFINEDREFERENCEASSERTIONRESULT_INCOMPATIBLETYPESTRUCTURE = _descriptor.Descriptor(
  name='IncompatibleTypeStructure',
  full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.IncompatibleTypeStructure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='structure', full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.IncompatibleTypeStructure.structure', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='structure', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=743,
  serialized_end=850,
)

_UNDEFINEDREFERENCEASSERTIONRESULT_SIMILARLYNAMEDSTRUCTURE = _descriptor.Descriptor(
  name='SimilarlyNamedStructure',
  full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.SimilarlyNamedStructure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='structure', full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.SimilarlyNamedStructure.structure', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='structure', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=852,
  serialized_end=957,
)

_UNDEFINEDREFERENCEASSERTIONRESULT = _descriptor.Descriptor(
  name='UndefinedReferenceAssertionResult',
  full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='violators', full_name='com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.violators', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='violators', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_UNDEFINEDREFERENCEASSERTIONRESULT_VIOLATOR, _UNDEFINEDREFERENCEASSERTIONRESULT_INCOMPATIBLETYPESTRUCTURE, _UNDEFINEDREFERENCEASSERTIONRESULT_SIMILARLYNAMEDSTRUCTURE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=957,
)


_STRUCTUREREFERENCE = _descriptor.Descriptor(
  name='StructureReference',
  full_name='com.intentionet.bfe.assertions.StructureReference',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reference_name', full_name='com.intentionet.bfe.assertions.StructureReference.reference_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='referenceName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='structure_type', full_name='com.intentionet.bfe.assertions.StructureReference.structure_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='structureType', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='usage_context', full_name='com.intentionet.bfe.assertions.StructureReference.usage_context', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='usageContext', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_lines', full_name='com.intentionet.bfe.assertions.StructureReference.file_lines', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='fileLines', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=960,
  serialized_end=1164,
)


_DEFINEDSTRUCTURE = _descriptor.Descriptor(
  name='DefinedStructure',
  full_name='com.intentionet.bfe.assertions.DefinedStructure',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='structure_name', full_name='com.intentionet.bfe.assertions.DefinedStructure.structure_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='structureName', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='structure_type', full_name='com.intentionet.bfe.assertions.DefinedStructure.structure_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='structureType', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_lines', full_name='com.intentionet.bfe.assertions.DefinedStructure.file_lines', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='fileLines', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=1167,
  serialized_end=1332,
)

_UNDEFINEDREFERENCEASSERTIONRESULT_VIOLATOR.fields_by_name['undefined_reference'].message_type = _STRUCTUREREFERENCE
_UNDEFINEDREFERENCEASSERTIONRESULT_VIOLATOR.fields_by_name['incompatible_type_structures'].message_type = _UNDEFINEDREFERENCEASSERTIONRESULT_INCOMPATIBLETYPESTRUCTURE
_UNDEFINEDREFERENCEASSERTIONRESULT_VIOLATOR.fields_by_name['similarly_named_structures'].message_type = _UNDEFINEDREFERENCEASSERTIONRESULT_SIMILARLYNAMEDSTRUCTURE
_UNDEFINEDREFERENCEASSERTIONRESULT_VIOLATOR.containing_type = _UNDEFINEDREFERENCEASSERTIONRESULT
_UNDEFINEDREFERENCEASSERTIONRESULT_INCOMPATIBLETYPESTRUCTURE.fields_by_name['structure'].message_type = _DEFINEDSTRUCTURE
_UNDEFINEDREFERENCEASSERTIONRESULT_INCOMPATIBLETYPESTRUCTURE.containing_type = _UNDEFINEDREFERENCEASSERTIONRESULT
_UNDEFINEDREFERENCEASSERTIONRESULT_SIMILARLYNAMEDSTRUCTURE.fields_by_name['structure'].message_type = _DEFINEDSTRUCTURE
_UNDEFINEDREFERENCEASSERTIONRESULT_SIMILARLYNAMEDSTRUCTURE.containing_type = _UNDEFINEDREFERENCEASSERTIONRESULT
_UNDEFINEDREFERENCEASSERTIONRESULT.fields_by_name['violators'].message_type = _UNDEFINEDREFERENCEASSERTIONRESULT_VIOLATOR
_STRUCTUREREFERENCE.fields_by_name['file_lines'].message_type = intentionet_dot_bfe_dot_proto_dot_datamodel_dot_config__text__pb2._FILELINES
_DEFINEDSTRUCTURE.fields_by_name['file_lines'].message_type = intentionet_dot_bfe_dot_proto_dot_datamodel_dot_config__text__pb2._FILELINES
DESCRIPTOR.message_types_by_name['UndefinedReferenceAssertionInput'] = _UNDEFINEDREFERENCEASSERTIONINPUT
DESCRIPTOR.message_types_by_name['UndefinedReferenceAssertionResult'] = _UNDEFINEDREFERENCEASSERTIONRESULT
DESCRIPTOR.message_types_by_name['StructureReference'] = _STRUCTUREREFERENCE
DESCRIPTOR.message_types_by_name['DefinedStructure'] = _DEFINEDSTRUCTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UndefinedReferenceAssertionInput = _reflection.GeneratedProtocolMessageType('UndefinedReferenceAssertionInput', (_message.Message,), {
  'DESCRIPTOR' : _UNDEFINEDREFERENCEASSERTIONINPUT,
  '__module__' : 'intentionet.bfe.proto.assertions.reference_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.bfe.assertions.UndefinedReferenceAssertionInput)
  })
_sym_db.RegisterMessage(UndefinedReferenceAssertionInput)

UndefinedReferenceAssertionResult = _reflection.GeneratedProtocolMessageType('UndefinedReferenceAssertionResult', (_message.Message,), {

  'Violator' : _reflection.GeneratedProtocolMessageType('Violator', (_message.Message,), {
    'DESCRIPTOR' : _UNDEFINEDREFERENCEASSERTIONRESULT_VIOLATOR,
    '__module__' : 'intentionet.bfe.proto.assertions.reference_pb2'
    # @@protoc_insertion_point(class_scope:com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.Violator)
    })
  ,

  'IncompatibleTypeStructure' : _reflection.GeneratedProtocolMessageType('IncompatibleTypeStructure', (_message.Message,), {
    'DESCRIPTOR' : _UNDEFINEDREFERENCEASSERTIONRESULT_INCOMPATIBLETYPESTRUCTURE,
    '__module__' : 'intentionet.bfe.proto.assertions.reference_pb2'
    # @@protoc_insertion_point(class_scope:com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.IncompatibleTypeStructure)
    })
  ,

  'SimilarlyNamedStructure' : _reflection.GeneratedProtocolMessageType('SimilarlyNamedStructure', (_message.Message,), {
    'DESCRIPTOR' : _UNDEFINEDREFERENCEASSERTIONRESULT_SIMILARLYNAMEDSTRUCTURE,
    '__module__' : 'intentionet.bfe.proto.assertions.reference_pb2'
    # @@protoc_insertion_point(class_scope:com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult.SimilarlyNamedStructure)
    })
  ,
  'DESCRIPTOR' : _UNDEFINEDREFERENCEASSERTIONRESULT,
  '__module__' : 'intentionet.bfe.proto.assertions.reference_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.bfe.assertions.UndefinedReferenceAssertionResult)
  })
_sym_db.RegisterMessage(UndefinedReferenceAssertionResult)
_sym_db.RegisterMessage(UndefinedReferenceAssertionResult.Violator)
_sym_db.RegisterMessage(UndefinedReferenceAssertionResult.IncompatibleTypeStructure)
_sym_db.RegisterMessage(UndefinedReferenceAssertionResult.SimilarlyNamedStructure)

StructureReference = _reflection.GeneratedProtocolMessageType('StructureReference', (_message.Message,), {
  'DESCRIPTOR' : _STRUCTUREREFERENCE,
  '__module__' : 'intentionet.bfe.proto.assertions.reference_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.bfe.assertions.StructureReference)
  })
_sym_db.RegisterMessage(StructureReference)

DefinedStructure = _reflection.GeneratedProtocolMessageType('DefinedStructure', (_message.Message,), {
  'DESCRIPTOR' : _DEFINEDSTRUCTURE,
  '__module__' : 'intentionet.bfe.proto.assertions.reference_pb2'
  # @@protoc_insertion_point(class_scope:com.intentionet.bfe.assertions.DefinedStructure)
  })
_sym_db.RegisterMessage(DefinedStructure)


# @@protoc_insertion_point(module_scope)
