"""
Trulioo Python SDK

Package version: 1.0.4
Trulioo OpenAPI version: v1
Generated by OpenAPI Generator version: 5.0.1
"""

from os import path
from setuptools import setup, find_packages

with open(
    path.join(path.abspath(path.dirname(__file__)), "README.md"), encoding="utf-8"
) as readme_file:
    long_description = readme_file.read()

setup(
    name="trulioo_sdk",
    version="1.0.4",
    description="Trulioo Python SDK",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="Trulioo",
    author_email="support@trulioo.com",
    url="https://github.com/Trulioo/sdk-python/",
    license="Apache-2.0",
    keywords=["Trulioo Python SDK"],
    packages=find_packages(exclude=["test*"]),
    python_requires=">=3.6",
    install_requires=[
        "urllib3 >= 1.25.3",
        "python-dateutil",
    ],
)
