
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-31T09:39:04+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "97527a519e0cef557e50bbad7c52047caa811981",
 "version": "2.6.0.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
