
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-26T09:35:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbc84a521776fe9b689b17ce9824dc7bd52e4115",
 "version": "1.0.0.post.dev23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
