[build-system]
requires = ['pip', 'setuptools', 'wheel', 'scikit-build', 'cmake', 'ninja', 'requests', 'dune-grid<=2.8.0.dev20210522', 'fenics-ufl==2019.1.0', 'dune-alugrid<=2.8.0.dev20210522', 'dune-istl<=2.8.0.dev20210522', 'dune-localfunctions<=2.8.0.dev20210522']
build-backend = 'setuptools.build_meta'
