[tool.poetry]
name = "machine-data-hub"
version = "0.1.1"
description = "Python-based Command Line Tool to use the Machine Data Hub"
homepage = "https://machinedatahub.ai/"
repository = "https://github.com/machine-data-hub"
documentation = "https://machine-data-hub.readthedocs.io/en/latest/?badge=latest"
readme = "README.md"
authors = ["ceciliabarnes <cbarnes7@uw.edu>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.7.1"
typer = "^0.3.2"
requests = "^2.25.1"
sphinx-rtd-theme = "^0.5.1"
tabulate = "^0.8.9"
tqdm = "^4.60.0"
rfc6266 = "^0.0.4"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pre-commit = "^2.9.3"
pytest = "^6.2.2"
coverage = {extras = ["toml"], version = "^5.4"}
pytest-cov = "^2.11.1"
pytest-mock = "^3.5.1"
responses = ">=0.13.3"

[tool.poetry.scripts]
mdh = "machine_data_hub.cli:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["machine_data_hub"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
