[tool.poetry]
name = "Lightshield"
version = "0.1.2b"
description = "Library part of the Lightshield tool."
license = 'Apache-2.0'
repository = 'https://github.com/LightshieldDotDev/Lightshield'
authors = ["Doctress <lightshielddev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "^3.7.4"
aioredis = "^1.3.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
