
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-24T13:37:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "29a558866020d75b0e58a67cc6fb4929b04b2c18",
 "version": "0.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
