
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-25T15:08:20+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "6855682dd8f2368e69c02eea99ef9e6593279bbc",
 "version": "2021.05.25post0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
