
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-27T19:42:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e77ba3cfb135662453587fd1f212c6caabf90df",
 "version": "0.3.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
