TEMPLATE_REPO_URLS = [
    "git@github.com:luke-lombardi/slai_template.git",
    "https://github.com/luke-lombardi/slai_template.git",
]  # TODO: move to slai github
NOTEBOOK_TRAINER_PREFIX = "keep"  # maybe rename to #export?
DEFAULT_TRAINER_TIMEOUT_S = 60 * 5  # 5 minutes
MODEL_WATCH_INTERVAL_S = 1
REQUIREMENTS_RETURN_CODE_SUCCESS = 0
REQUIREMENTS_RETURN_CODE_MISSING_DEP = 1
REQUIREMENTS_RETURN_CODE_IMPORT_ERROR = 2
REQUIREMENTS_RETURN_CODE_FILE_NOT_FOUND_ERROR = 3
REQUIREMENTS_RETURN_CODE_UNKNOWN_ERROR = 4
REQUIREMENTS_RETURN_CODE_EXIT = 5
