[tool.poetry]
name = "py-zapi"
version = "0.1.2"
description = "ZeroMQ Devices API"
license = "MIT"
authors = ["Geoff Johnson <geoff.jay@gmail.com>"]
packages = [{ include = "zapi" }]
readme = "README.md"
homepage = "https://gitlab.com/plantd/py-zapi"
repository = "https://gitlab.com/plantd/py-zapi"
classifiers = [
    "Topic :: Software Development :: Build Tools",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
include = [
    "LICENSE"
]

[tool.poetry.dependencies]
python = "^3.8"
pyzmq = ">=22.0"

[tool.poetry.dev-dependencies]
bandit = "^1.7.0"
black = "20.8b1"
codecov = "^2.0.15"
coverage = "^5.5"
interrogate = "^1.3.2"
isort = "^5.8.0"
pre-commit = "^2.12.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'
exclude = '''
/(
  | \.eggs
  | \.git
  | \.tox
  | \.venv
  | _build
  | build
  | changelog
  | dist
)/
'''

[tool.interrogate]
ignore-init-method = true
ignore-init-module = false
ignore-magic = true
ignore-semiprivate = false
ignore-private = false
ignore-property-decorators = false
ignore-module = false
fail-under = 75
exclude = [
    "docs",
    "tests",
    # wildcards don't work on paths
    "examples/",
]
ignore-regex = []
whitelist-regex = []
verbose = 0
quiet = false
color = true

[tool.isort]
multi_line_output = 3
line_length = 120
known_first_party = [ "tests" ]
include_trailing_comma = true
order_by_type = false
