
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-26T08:43:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "1b96922dfb7ccb7a37f483ee6e0fd2635923c1c9",
 "version": "2021.5.26"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
