
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-05-30T18:34:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5407d535d6690638cd23607826b7a355add8df2c",
 "version": "2.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
